quarkus.http.port=9090

quarkus.datasource.db-kind=oracle 
quarkus.hibernate-orm.database.generation=none
quarkus.datasource.username=cooponepd
quarkus.datasource.password=pcACHuyAe25kQSmY
quarkus.datasource.jdbc.url=jdbc:oracle:thin:@192.168.40.30:1521:dbpd1
quarkus.datasource.jdbc.max-size=16


quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.headers=Content-Type
quarkus.http.cors.methods=GET,POST,PUT,DELETE


# Dirección del broker Kafka
kafka.bootstrap.servers=localhost:9092

